### PR TITLE
Add _get_vcr to customize VCR

### PR DESCRIPTION
**Pull request by agriffis**
This is especially for adding matchers as a replacement for #3

### CODE REVIEW

**Comment by rossgray** [comment]
Looks good to me @agriffis. Thanks!

**Comment by agriffis** [comment]
@rossgray Thanks. I'll make a release with this change when I get a chance in the next week.

**Comment by rossgray** [comment]
@agriffis - any idea when you will be able to release this?

**Comment by agriffis** [comment]
Thanks for the nudge @rossgray. Released as 0.1.5 on PyPI now.

**Comment by rossgray** [comment]
Thanks a lot @agriffis

**Pull request merged**
